/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @bri ef          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <systick.h>
/* RCC */
#define RCC_BASE 0x40023800
#define RCC_AHB1ENR (*(volatile uint32_t *)(RCC_BASE + 0x30))
#define GPIOA_BASE  0x40020000
#define GPIOA_MODER (*(volatile uint32_t *)(GPIOA_BASE + 0))
#define GPIOA_ODR (*(volatile uint32_t *)( GPIOA_BASE + 0x14 ))



#ifndef BLINK_DELAY_MS
#define BLINK_DELAY_MS 200
#endif

int main(void)
{
    /* Enable GPIOA and GPIOC clocks */

    RCC_AHB1ENR |= (1<<0);


    /* PA5 Output */

    GPIOA_MODER &= ~(3<<10);
    GPIOA_MODER |=  (1<<10);

    SysTick_Init();
    while(1)
    {
		if(SysTick_ms_delay(BLINK_DELAY_MS))
		{
				GPIOA_ODR ^= (1<<5);
		}
    }
}
